# Generated by Django 3.2.7 on 2021-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], default='0'),
        ),
    ]
