# Generated by Django 3.2.7 on 2021-10-01 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20211001_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 14, 43, 40, 900565, tzinfo=utc)),
        ),
    ]
